const KEY='agendaEF_v1';let db=JSON.parse(localStorage.getItem(KEY)||'{"tasks":[],"subjects":[],"materials":[],"grades":[]}');let cal=new Date();
const $=id=>document.getElementById(id), save=()=>{localStorage.setItem(KEY,JSON.stringify(db));render()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));render()}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
function openModal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}
function openTask(){openModal('Nueva tarea',`<form class="form" onsubmit="addTask(event)"><label>Nombre<input id="tn" required placeholder="Ej. Planeación de Educación Física"></label><div class="row"><label>Materia<select id="ts"><option value="">Sin materia</option>${db.subjects.map(s=>`<option>${esc(s.name)}</option>`).join('')}</select></label><label>Entrega<input id="td" type="date" required></label></div><label>Prioridad<select id="tp"><option>Alta</option><option selected>Normal</option><option>Baja</option></select></label><label>Notas<textarea id="tx" rows="3" placeholder="Detalles..."></textarea></label><button class="primary">Guardar tarea</button></form>`)}
function addTask(e){e.preventDefault();db.tasks.push({id:Date.now(),name:tn.value,subject:ts.value,date:td.value,priority:tp.value,notes:tx.value,done:false});closeModal();save()}
function toggleTask(id){let t=db.tasks.find(x=>x.id==id);if(t)t.done=!t.done;save()}function delTask(id){db.tasks=db.tasks.filter(x=>x.id!=id);save()}
function taskHTML(t){return `<div class="item"><div><h3>${t.done?'✅ ':''}${esc(t.name)}</h3><p>${esc(t.subject||'Sin materia')} · ${esc(t.date||'Sin fecha')}${t.notes?' · '+esc(t.notes):''}</p></div><div class="actions"><span class="badge">${esc(t.priority)}</span><button onclick="toggleTask(${t.id})">${t.done?'Desmarcar':'Completar'}</button><button onclick="delTask(${t.id})">Eliminar</button></div></div>`}
function renderTasks(){let q=($('taskSearch')?.value||'').toLowerCase(),f=$('taskFilter')?.value||'all';let a=db.tasks.filter(t=>(t.name+' '+t.subject).toLowerCase().includes(q)).filter(t=>f==='all'||(f==='done'?t.done:!t.done)).sort((a,b)=>a.date.localeCompare(b.date));$('taskList').innerHTML=a.length?a.map(taskHTML).join(''):'<div class="card">No hay tareas con estos filtros.</div>'}
function openSubject(){openModal('Nueva materia',`<form class="form" onsubmit="addSubject(event)"><label>Materia<input id="sn" required placeholder="Ej. Anatomía"></label><label>Profesor/a<input id="st" placeholder="Opcional"></label><button class="primary">Guardar materia</button></form>`)}
function addSubject(e){e.preventDefault();db.subjects.push({id:Date.now(),name:sn.value,teacher:st.value});closeModal();save()}function delSubject(id){db.subjects=db.subjects.filter(x=>x.id!=id);save()}
function renderSubjects(){$('subjectList').innerHTML=db.subjects.length?db.subjects.map(s=>`<div class="item"><div><h3>📚 ${esc(s.name)}</h3><p>${esc(s.teacher||'Profesor/a no registrado')}</p></div><div class="actions"><button onclick="delSubject(${s.id})">Eliminar</button></div></div>`).join(''):'<div class="card">Todavía no tienes materias.</div>'}
function openMaterial(){openModal('Nuevo material',`<form class="form" onsubmit="addMaterial(event)"><label>Material<input id="mn" required placeholder="Ej. Silbato, conos, libreta..."></label><label>Uso o materia<input id="mu" placeholder="Ej. Práctica de fútbol"></label><label>¿Ya lo tienes?<select id="mh"><option value="no">No</option><option value="yes">Sí</option></select></label><button class="primary">Guardar material</button></form>`)}
function addMaterial(e){e.preventDefault();db.materials.push({id:Date.now(),name:mn.value,use:mu.value,have:mh.value==='yes'});closeModal();save()}function toggleMaterial(id){let m=db.materials.find(x=>x.id==id);m.have=!m.have;save()}function delMaterial(id){db.materials=db.materials.filter(x=>x.id!=id);save()}
function renderMaterials(){$('materialList').innerHTML=db.materials.length?db.materials.map(m=>`<div class="item"><div><h3>${m.have?'✅':'⬜'} ${esc(m.name)}</h3><p>${esc(m.use||'Sin uso especificado')}</p></div><div class="actions"><button onclick="toggleMaterial(${m.id})">${m.have?'Marcar pendiente':'Ya lo tengo'}</button><button onclick="delMaterial(${m.id})">Eliminar</button></div></div>`).join(''):'<div class="card">Todavía no tienes materiales.</div>'}
function openGrade(){openModal('Nueva calificación',`<form class="form" onsubmit="addGrade(event)"><label>Materia<input id="gs" required placeholder="Ej. Bases de la Educación Física"></label><label>Actividad<input id="ga" required placeholder="Ej. Examen 1"></label><label>Calificación<input id="gg" required type="number" min="0" max="10" step=".1"></label><button class="primary">Guardar calificación</button></form>`)}
function addGrade(e){e.preventDefault();db.grades.push({id:Date.now(),subject:gs.value,activity:ga.value,grade:Number(gg.value)});closeModal();save()}function delGrade(id){db.grades=db.grades.filter(x=>x.id!=id);save()}
function renderGrades(){let avg=db.grades.length?db.grades.reduce((a,x)=>a+x.grade,0)/db.grades.length:null;$('average').textContent=avg===null?'—':avg.toFixed(2);$('gradeList').innerHTML=db.grades.length?db.grades.map(g=>`<div class="item"><div><h3>${esc(g.subject)}</h3><p>${esc(g.activity)}</p></div><div class="actions"><span class="badge">${g.grade.toFixed(1)}</span><button onclick="delGrade(${g.id})">Eliminar</button></div></div>`).join(''):'<div class="card">Todavía no registras calificaciones.</div>'}
function month(n){cal.setMonth(cal.getMonth()+n);renderCalendar()}
function renderCalendar(){let y=cal.getFullYear(),m=cal.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;$('monthTitle').textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(cal);let out=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<div class="dayname">${x}</div>`).join('');for(let i=0;i<start;i++)out+='<div></div>';let now=new Date();for(let d=1;d<=last.getDate();d++){let iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,today=now.getFullYear()==y&&now.getMonth()==m&&now.getDate()==d,events=db.tasks.filter(t=>t.date===iso);out+=`<div class="day ${today?'today':''}"><b>${d}</b>${events.map(t=>`<div class="event">${esc(t.name)}</div>`).join('')}</div>`}$('calendar').innerHTML=out}
function renderHome(){let p=db.tasks.filter(t=>!t.done),now=new Date(),end=new Date();end.setDate(now.getDate()+7);let soon=p.filter(t=>t.date&&new Date(t.date+'T23:59:59')>=new Date(now.toDateString())&&new Date(t.date+'T23:59:59')<=end).length;$('pending').textContent=p.length;$('soon').textContent=soon;$('subjectsN').textContent=db.subjects.length;$('materialsN').textContent=db.materials.length;$('homeTasks').innerHTML=p.slice(0,6).map(taskHTML).join('')||'<p style="color:var(--muted)">🎉 No tienes tareas pendientes.</p>'}
function render(){renderHome();renderTasks();renderSubjects();renderMaterials();renderGrades();renderCalendar()}
$('dateText').textContent=new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());render();
if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js');
